### ISSUE TITLE
Add Discord

### ISSUE THREAD

**Issue by iMplode-nZ** [bonsairobo/building-blocks#1]
This project seems nice; I think it should have some sort of chat (it seems Discord is generally accepted among the rust community)

**Comment by bonsairobo** [comment]
Hey thanks for showing interest. I'd be happy to make a discord server. I'll post here when it's ready.

**Comment by bonsairobo** [comment]
It exists. I also added a shield to the README.

https://discordapp.com/invite/gVMxUm
