### ISSUE TITLE
feature-gate simdnoise

### ISSUE THREAD

**Issue by eadf** [bonsairobo/building-blocks#29]
Can simdnoise be feature gated in crates/utilities/Cargo.toml?

Cause it does *not* compile on a M1 Mac. There is a PR for it to be fixed, but it's getting old : https://github.com/jackmott/rust-simd-noise/pull/34

When I try to run `cargo test` on my M1 I get hundreds of errors like this:
```
323 | #[target_feature(enable = "sse4.1")]
        |              ^^^^^^^^^^^^^^^^^ `sse4.1` is not valid for this target```

**Comment by bonsairobo** [comment]
Sure thing! I just pushed a commit for this.
