### ISSUE TITLE
no function or associated item named `from_all_compressed` found for struct `compressible_map::CompressibleMap<_, _, _, std::hash::BuildHasherDefault<fnv::FnvHasher>>` in the current scope

### ISSUE THREAD

**Issue by Levijatan** [bonsairobo/building-blocks#5]
building_blocks_storage-0.2.0\src\chunk_map.rs:467:41
    |
467 |             chunks: CompressibleFnvMap::from_all_compressed(params, all_compressed),
    |                                         ^^^^^^^^^^^^^^^^^^^ function or associated item not found in `compressible_map::CompressibleMap<_, _, _, std::hash::BuildHasherDefault<fnv::FnvHasher>>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `building_blocks_storage`.dHasherDefault<fnv::FnvHasher>>`

When trying to build with 0.2

**Comment by bonsairobo** [comment]
Just so people know, this is fixed by doing a `cargo update`.
